---
- name: Verify
  hosts: all
  tasks:
    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: Populate activemq facts
      middleware_automation.amq.activemq_facts:
        base_url: http://localhost:8161
        auth_username: amq-broker
        auth_password: amq-broker
        validate_certs: false

    - name: Check if amq-broker service is started
      ansible.builtin.assert:
        that:
          - ansible_facts.services["amq-broker.service"]["state"] == "running"
          - ansible_facts.services["amq-broker.service"]["status"] == "enabled"

    - name: Read content of instance1 logs
      ansible.builtin.slurp:
        src: /var/log/activemq/amq-broker/artemis.log
      register: slurped_log_instance

    - name: Check cluster status
      block:
        - name: Check live-only on instance1
          ansible.builtin.assert:
            that:
              - "'live Message Broker is starting' in slurped_log_instance.content | b64decode or 'Primary message broker is starting' in slurped_log_instance.content | b64decode"
            quiet: true

    - name: Check cluster status via jolokia facts
      ansible.builtin.assert:
        that:
          - ansible_facts.activemq.Active == true
          - ansible_facts.activemq.Backup == false
          - ansible_facts.activemq.Clustered == false
          - ansible_facts.activemq.SharedStore == false
          - ansible_facts.activemq.HAPolicy == "Primary Only"
