---
- name: Converge
  hosts: all
  gather_facts: yes
  vars:
    activemq_config_override_template: 'broker.xml.j2'
    activemq_jvm_package: java-11-openjdk-headless
    activemq_properties_file: test.properties
  roles:
    - middleware_automation.amq.activemq
