---
### Version settings
activemq_version: 2.18.0
activemq_archive: "apache-artemis-{{ activemq_version }}-bin.zip"
activemq_download_url: "https://archive.apache.org/dist/activemq/activemq-artemis/{{ activemq_version }}/{{ activemq_archive }}"  
activemq_installdir: "{{ activemq_dest }}/apache-artemis-{{ activemq_version }}"

### Install location and service settings
activemq_dest: /opt/amq
activemq_offline_install: False
activemq_config_dir: "conf"
activemq_config_xml: amq-broker.xml
activemq_config_override_template: ''
activemq_service_user: amq-broker
activemq_service_group: amq-broker
activemq_instance_name: amq-broker
activemq_instance_username: amq-broker
activemq_instance_password: amq-broker
activemq_instance_anonymous: False
activemq_service_pidfile: data/artemis.pid
activemq_configure_firewalld: False

### Common configuration settings
activemq_bind_address: 0.0.0.0
activemq_host: localhost
activemq_http_port: 8161
activemq_jolokia_url: "http://{{ activemq_host }}:{{ activemq_http_port }}/console/jolokia"
activemq_console_url: "http://{{ activemq_host }}:{{ activemq_http_port }}/console/"
activemq_jvm_package: java-11-openjdk-headless
activemq_java_home:
activemq_java_opts: "-Xms1024m -Xmx2048m"
activemq_port: 61616        # for protocols [CORE,MQTT,AMQP,STOMP,HORNETQ,OPENWIRE]
activemq_port_hornetq: 5445 # for protocols [HORNETQ,STOMP]
activemq_port_amqp: 5672    # for protocols [AMQP]
activemq_port_mqtt: 1883    # for protocols [MQTT]
activemq_port_stomp: 61613  # for protocols [STOMP]
activemq_name: 'Apache ActiveMQ'
activemq_service_name: activemq

### Enable configuration for high availability
activemq_ha_enabled: False
activemq_cluster_user: amq-cluster-user
activemq_cluster_pass: amq-cluster-pass
activemq_cluster_maxhops: 1
activemq_cluster_lb_policy: ON_DEMAND
activemq_replicate: False
activemq_replicated: False
# cluster discovery: ['jgroups' for shared file ping, 'multicast' for UDP multicast, 'static' for static declaration]
activemq_cluster_discovery: static

### Enable database configuration for JDBC persistence
activemq_db_enabled: False

### Enable TLS
activemq_tls_enabled: False
activemq_tls_keystore_path: identity.ks
activemq_tls_keystore_password: changeme
activemq_tls_keystore_dest: "{{ activemq_dest }}/{{ activemq_instance_name }}/etc/identity.ks"

# Mutual authentication (requires TLS)
activemq_tls_mutual_authentication: False
activemq_tls_truststore:
activemq_tls_truststore_password:
activemq_tls_truststore_dest: "{{ activemq_dest }}/{{ activemq_instance_name }}/etc/trust.ks"

# Users
# list of users the create, user is not created if password empty; list of (user,password,roles) dicts
# .roles is a list of activemq_roles.name
activemq_users:
  - user: "{{ activemq_instance_username }}"
    password: "{{ activemq_instance_password }}"
    roles: [ amq ]

# Roles
# .permissions is subset of:
# [ createNonDurableQueue, deleteNonDurableQueue, createDurableQueue, deleteDurableQueue, createAddress, deleteAddress, consume, browse, send, manage ]
activemq_roles:
  - name: amq
    match: '#'
    permissions: [ createNonDurableQueue, deleteNonDurableQueue, createDurableQueue, deleteDurableQueue, createAddress, deleteAddress, consume, browse, send, manage ]

# NIO option
activemq_nio_enabled: False

## Shared Storage
activemq_shared_storage: False
activemq_shared_storage_path: data/shared

## Ports
activemq_ports_offset_enabled: False
activemq_ports_offset: 0

# Queues
activemq_disable_destination_autocreate: True
activemq_queues: queue.in,queue.out

# Protocol disablement
activemq_disable_amqp_protocol: False
activemq_disable_hornetq_protocol: False
activemq_disable_mqtt_protocol: False
activemq_disable_stomp_protocol: False

# Logging
activemq_enable_audit: False
activemq_logger_level: INFO
activemq_logger_core_server_level: INFO
activemq_logger_journal_level: INFO
activemq_logger_utils_level: INFO
activemq_logger_utils_critical_level: INFO
activemq_logger_jms_level: INFO
activemq_logger_integration_bootstrap_level: INFO
activemq_logger_jetty_level: WARN
activemq_logger_curator_level: WARN
activemq_logger_zookeeper_level: ERROR

# Metrics
activemq_jmx_exporter_port: 18080
activemq_jmx_exporter_config_path: "{{ activemq_dest }}/{{ activemq_instance_name }}/etc/jmx_exporter.yml"
activemq_jmx_exporter_enabled: False
activemq_prometheus_enabled: False

### Contoller defaults
activemq_local_archive_repository: "{{ lookup('env', 'PWD') }}"