---
- name: Converge
  hosts: all
  gather_facts: yes
  vars:
    activemq_enable: True
    activemq_offline_install: True
    activemq_users:
    - user: amq
      password: amqbrokerpass
      roles: [ amq ]
  collections:
    - middleware_automation.redhat_csp_download
  tasks:
    - name: Include role for broker upgrade
      ansible.builtin.include_role:
        name: amq_broker
      vars:
        activemq_version: "{{ '2.20.0' if amq-broker-7.10.0-bin.zip' is not exists else '7.10.0' }}"
