---
- name: Converge
  hosts: all
  gather_facts: yes
  vars:
    activemq_enable: True
    activemq_offline_install: True
    activemq_users:
    - user: amq
      password: amqbrokerpass
      roles: [ amq ]
  collections:
    - middleware_automation.redhat_csp_download
  tasks:
    - name: Include AMQ role for 7.10 upgrade
      ansible.builtin.include_role:
        name: amq_broker
      vars:
        activemq_version: 7.10.0
      when: "amq-broker-7.10.0-bin.zip is exists"