---
- name: Converge
  hosts: all
  gather_facts: yes
  vars:
    activemq_users:
    - user: amq
      password: amqbrokerpass
      roles: [ amq ]
  collections:
    - middleware_automation.redhat_csp_download
  tasks:
    - name: Include role for broker upgrade
      ansible.builtin.include_role:
        name: activemq
      vars:
        activemq_version: "{{ '7.10.0' if amq_broker_enable is defined and amq_broker_enable else '2.20.0' }}"
