---
- name: Verify
  hosts: all
  tasks:
    - name: Check local download archive path
      ansible.builtin.stat:
        path: "{{ activemq_local_archive_repository }}"
      register: local_path
      delegate_to: localhost    
    - name: Check archive for 7.9.4
      ansible.builtin.stat:
        path: "{{ local_path.stat.path }}/amq-broker-7.9.4-bin.zip"
      register: local_archive_path
      delegate_to: localhost    
    - name: Verify only if zipfiles present
      when: local_archive_path.stat.exists
      block:
        - name: Populate service facts
          ansible.builtin.service_facts:
        - name: Check if amq-broker service is started
          ansible.builtin.assert:
            that:
              - ansible_facts.services["amq-broker.service"]["state"] == "running"
              - ansible_facts.services["amq-broker.service"]["status"] == "enabled"
        - name: Read content of logs
          slurp:
            src: /var/log/amq_broker/amq-broker/artemis.log
          register: slurped_log
        - name: Check status
          assert:
            that:
              - "'Server is now live' in slurped_log.content|b64decode"
            quiet: true