---
- name: Create connector configuration string
  ansible.builtin.set_fact:
    connectors: "{{ connectors | default([]) + [ lookup('template', 'connectors.broker.xml.j2') ] }}"
  loop: "{{ activemq_connectors }}"
  loop_control:
    loop_var: connector
    label: "{{ connector.name }}"

- name: Create connector configuration in broker.xml
  xml:
    path: "{{ activemq.instance_home }}/etc/broker.xml"
    xpath: /conf:configuration/core:core/core:connectors
    input_type: xml
    set_children: "{{ connectors }}"
    namespaces:
      conf: urn:activemq
      core: urn:activemq:core
    pretty_print: yes
  become: yes
  notify:
    - restart amq_broker
