---
- name: Create federations configuration string
  ansible.builtin.set_fact:
    federations: "{{ federations | default([]) + [ lookup('template', 'federations.broker.xml.j2') ] }}"
  loop: "{{ amq_broker_federations }}"
  loop_control:
    loop_var: federation
    label: "{{ federation.name }}"

- name: Ensure federations element exists in broker.xml
  redhat.runtimes_common.xml:
    path: "files/broker.xml"
    xpath: /conf:configuration/core:core/core:federations
    input_type: xml
    state: present
    namespaces:
      conf: urn:activemq
      core: urn:activemq:core
    pretty_print: yes

- name: Create federations configuration in broker.xml
  redhat.runtimes_common.xml:
    path: "files/broker.xml"
    xpath: /conf:configuration/core:core/core:federations
    input_type: xml
    set_children: "{{ federations }}"
    namespaces:
      conf: urn:activemq
      core: urn:activemq:core
    pretty_print: yes
