---
# - name: Validate admin console password
#   ansible.builtin.assert:
#     that:
#       - activemq_admin_password | length > 12
#     quiet: True
#     fail_msg: "The console administrator password is empty or invalid. Please set the activemq_admin_password variable to a 16+ char long string"
#     success_msg: "{{ 'Console administrator password OK' }}"

# - name: Validate configuration
#   ansible.builtin.assert:
#     that:
#       - (activemq_ha_enabled and activemq_db_enabled) or (not activemq_ha_enabled and activemq_db_enabled) or (not activemq_ha_enabled and not activemq_db_enabled)
#     quiet: True
#     fail_msg: "Cannot install HA setup without a backend database service. Check activemq_ha_enabled and activemq_db_enabled"
#     success_msg: "{{ 'Configuring HA' if activemq_ha_enabled else 'Configuring standalone' }}"

- name: Validate credentials
  ansible.builtin.assert:
    that:
      - (rhn_username is defined and amq_broker_enable is defined and amq_broker_enable) or amq_broker_enable is not defined or not amq_broker_enable or activemq_offline_install
      - (rhn_password is defined and amq_broker_enable is defined and amq_broker_enable) or amq_broker_enable is not defined or not amq_broker_enable or activemq_offline_install
    quiet: True
    fail_msg: "Cannot install Red Hat AMQ Broker without RHN credentials. Check rhn_username and rhn_password are defined or use offline installation"
    success_msg: "{{ 'Installing ' + activemq.service_name }}"

- name: Validate TLS config
  ansible.builtin.assert:
    that:
      - activemq_tls_truststore_path is defined
      - activemq_tls_truststore_password is defined
      - activemq_tls_keystore_path is defined
      - activemq_tls_keystore_password is defined
  when: activemq_tls_enabled

- name: Validate TLS mutual auth config
  ansible.builtin.assert:
    that:
      - activemq_tls_truststore_path is defined
      - activemq_tls_truststore_password is defined
      - activemq_tls_keystore_path is defined
      - activemq_tls_keystore_password is defined
      - activemq_tls_enabled
  when: activemq_tls_mutual_authentication

- name: Ensure required packages are installed
  ansible.builtin.include_tasks: fastpackages.yml
  vars:
    packages_list:
      - "{{ activemq_jvm_package }}"
      - unzip
      - procps-ng
      - initscripts
      - libaio
      - python3-lxml

- name: Ensure required packages are installed
  ansible.builtin.dnf:
    name: prometheus-jmx-exporter
    state: present
  when: activemq_jmx_exporter_enabled
