---
- name: "Start and enable instance {{ activemq.instance_name }} for {{ activemq.service_name }} service"
  ansible.builtin.systemd:
    name: "{{ activemq.instance_name }}"
    enabled: yes
    state: started
  become: yes
