---
- name: Converge
  hosts: all
  gather_facts: yes
  vars:
    activemq_ha_enabled: true
    activemq_disable_hornetq_protocol: true
    activemq_disable_mqtt_protocol: true
    activemq_shared_storage: true
    activemq_configure_firewalld: false  
  collections:
    - middleware_automation.redhat_csp_download
  roles:
    - activemq
