---
- name: Verify
  hosts: all
  tasks:
    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: Check if amq-broker service is started
      ansible.builtin.assert:
        that:
          - ansible_facts.services["amq-broker.service"]["state"] == "running"
          - ansible_facts.services["amq-broker.service"]["status"] == "enabled"

    - name: Read content of instance1 logs
      slurp:
        src: /var/log/activemq/amq-broker/artemis.log
      register: slurped_log_instance1
      delegate_to: instance1

    - name: Read content of instance1 logs
      slurp:
        src: /var/log/activemq/amq-broker/artemis.log
      register: slurped_log_instance2
      delegate_to: instance2

    - name: Check cluster status
      assert:
        that:
          - "'Waiting indefinitely to obtain live lock' in slurped_log_instance2.content|b64decode"
          - "'Server is now live' in slurped_log_instance1.content|b64decode"
        quiet: true