---
- name: Prepare
  hosts: all
  tasks:
    - name: "Run preparation common to all scenario"
      ansible.builtin.include_tasks: ../prepare.yml
      vars:
        assets:
          - "{{ assets_server }}/amq/broker/7.10.2/amq-broker-7.10.2-bin.zip"
