---
### required variables


### internal variables
activemq:
  home: "{{ activemq_installdir }}"
  version: "{{ activemq_version }}"
  download_url: "{{ activemq_download_url }}"
  bundle: "{{ activemq_archive }}"
  name: "{{ activemq_name }}"
  service_name: "{{ activemq_service_name }}"
  instance_name: "{{ activemq_instance_name }}"
  instance_home: "{{ activemq_dest }}/{{ activemq_instance_name }}"
  
