---
- name: Set masked user password
  block:
    - name: Get masked password for user
      ansible.builtin.command: "{{ activemq.instance_home }}/bin/artemis mask -- '{{ item.password }}'"
      become: True
      become_user: "{{ activemq_service_user }}"
      register: mask_pwd
      changed_when: False
      no_log: True
    - name: Add masked password to users list
      ansible.builtin.set_fact:
        activemq_masked_users: "{{ activemq_masked_users | default([]) + [{ 'user': item.user, 'password': mask_pwd.stdout | replace('result: ',''), 'roles': item.roles }] }}"
      no_log: True
      when: item.password is defined and item.password | length > 0
